### ISSUE TITLE
You do not have permission to pass this beta header: oxxo_beta is broken

### ISSUE THREAD

**Issue by victorct-pronto** [stripe/stripe-python#664] opened 2020-07-08 03:05 UTC
Library version: 2.48.0
API Version: 2020-03-02; oxxo_beta=v1

So I use an application where I have two different stripe accounts (One for connect and other for customers), and on both of the apps I have the OXXO Beta Active (Mexico City), the problem is, whenever I do a request with one of the following methods: 

- `stripe.Account.create_external_account`
- `stripe.Account.modify`

I'm getting the next error `Invalid Stripe API version: 2020-03-02; oxxo_beta=v1. You do not have permission to pass this beta header: oxxo_beta. If you have any questions, we can help at https://support.stripe.com/.`

The problem is, it only happens with these requests, if I use on of the following methods for example:

- `stripe.Customer.create_source`
- `stripe.Account.create`
- `stripe.Customer.create`

I get a successful response, here are some examples of how I'm using them:

`stripe.Customer.create_source`: 

```
stripe.Customer.create_source(customer_id, source=card_token, stripe_version="2020-03-02; oxxo_beta=v1",
                                             api_key=ENV.STRIPE_DRIVER_SECRET_KEY)
```

`stripe.Account.create_external_account`:

```
external_account = stripe.Account.create_external_account(
            account_id,
            external_account=external_account,
            stripe_version="2020-03-02; oxxo_beta=v1",
            api_key=ENV.STRIPE_DRIVER_SECRET_KEY
        )
```

**Comment by victorct-pronto** [comment] 2020-07-08 03:08
And If I remove them, only on those methods, they work as expected.

**Comment by victorct-pronto** [comment] 2020-07-08 03:09
Here is a request of one of the methods:

```
- request:
    body: null
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Authorization:
      - Bearer sk_test_xxxxxx
      Connection:
      - keep-alive
      Content-Length:
      - '0'
      Content-Type:
      - application/x-www-form-urlencoded
      Idempotency-Key:
      - d332c529-6b78-41f8-86bf-602fdf187747
      Stripe-Version:
      - 2020-03-02; oxxo_beta=v1
      User-Agent:
      - Stripe/v1 PythonBindings/2.48.0
      X-Stripe-Client-Telemetry:
      - '{"last_request_metrics": {"request_id": "req_XGE9Zz3T47UqhT", "request_duration_ms":
        3528}}'
      X-Stripe-Client-User-Agent:
      - '{"bindings_version": "2.48.0", "lang": "python", "publisher": "stripe", "httplib":
        "requests", "lang_version": "3.7.7", "platform": "Linux-4.19.76-linuxkit-x86_64-with-debian-10.3",
        "uname": "Linux 67263add3a3e 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC
        2020 x86_64 "}'
    method: POST
    uri: https://api.stripe.com/v1/accounts/acct_1H2TAlKJlYICbWH7
  response:
    body:
      string: "{\n  \"error\": {\n    \"message\": \"Invalid Stripe API version: 2020-03-02;\
        \ oxxo_beta=v1. You do not have permission to pass this beta header: oxxo_beta.\
        \ If you have any questions, we can help at https://support.stripe.com/.\"\
        ,\n    \"type\": \"invalid_request_error\"\n  }\n}\n"
    headers:
      Connection:
      - keep-alive
      Content-Length:
      - '264'
      Content-Type:
      - application/json
      Date:
      - Wed, 08 Jul 2020 02:44:10 GMT
      Server:
      - nginx
      Strict-Transport-Security:
      - max-age=31556926; includeSubDomains; preload
      access-control-allow-credentials:
      - 'true'
      access-control-allow-methods:
      - GET, POST, HEAD, OPTIONS, DELETE
      access-control-allow-origin:
      - '*'
      access-control-expose-headers:
      - Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required
      access-control-max-age:
      - '300'
      cache-control:
      - no-cache, no-store
      stripe-account:
      - acct_1H2TAlKJlYICbWH7
      stripe-version:
      - 2020-03-02; oxxo_beta=v1
    status:
      code: 400
      message: Bad Request
```

And here is a picture of the beta being enabled: 
![image](https://user-images.githubusercontent.com/56981448/86870712-865f9c00-c09e-11ea-820f-0cf44479c78a.png)

**Comment by remi-stripe** [comment] 2020-07-08 04:24
@victorct-pronto Thanks for the report! This isn't really a bug with stripe-python so I'm going to close this out. I'd recommend talking with our support team instead for features like this that are in private beta.

To unblock you though, the problem is that you are making requests on connected accounts when you use those 2 specific requests and your account only has the OXXO beta on the main account not your connected accounts. What you should do here is ensure you don't pass the beta flag in requests made on behalf of connected accounts. The best solution is really to only pass the custom version for calls that interact with OXXO PaymentMethod or PaymentIntent for example but not when interacting with other APIs!

**Closed by remi-stripe** 2020-07-08 04:24 UTC

**Comment by victorct-pronto** [comment] 2020-07-08 17:53
> @victorct-pronto Thanks for the report! This isn't really a bug with stripe-python so I'm going to close this out. I'd recommend talking with our support team instead for features like this that are in private beta.
> 
> To unblock you though, the problem is that you are making requests on connected accounts when you use those 2 specific requests and your account only has the OXXO beta on the main account not your connected accounts. What you should do here is ensure you don't pass the beta flag in requests made on behalf of connected accounts. The best solution is really to only pass the custom version for calls that interact with OXXO PaymentMethod or PaymentIntent for example but not when interacting with other APIs!

Awesome, thank you so much for the response, the documentation wasn't very clear that this could be used as different APIs
