### ISSUE TITLE
Cannot install since integration of poetry

### ISSUE THREAD

**Issue by iamareebjamal** [stripe/stripe-python#582] opened 2019-06-03 16:32 UTC
Build is failing in alpine since integration of poetry

Library Version: 2.29.3

https://github.com/sdispater/poetry/issues/760

Note that I am not using --no-binary CL argument, this is just standard pip install -r requirements.txt in alpine (docker)

Not that I have any say in the matter, but this could have been integrated in a minor upgrade, i.e., 2.30.x, and not a patch upgrade: 2.29.1 -> 2.29.2 :)

Logs:
```
Collecting stripe~=2.29 (from -r /requirements/common.txt (line 29))
Downloading https://files.pythonhosted.org/packages/68/26/cc458011dd3ef64ee7b3072c03a3fa31ff25ae2bdb19c8e7946949a6b5b0/stripe-2.29.3.tar.gz (208kB)
Installing build dependencies: started
Installing build dependencies: still running...
Installing build dependencies: finished with status 'error'
/usr/local/lib/python3.6/site-packages/pip/_internal/commands/install.py:244: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
cmdoptions.check_install_build_global(options)
ERROR: Complete output from command /usr/local/bin/python /usr/local/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-thr9o4r9/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'poetry>=0.12':
ERROR: Collecting poetry>=0.12
Downloading https://files.pythonhosted.org/packages/1f/69/96862c449a3b586c16cdedd97df1c40c94569fec99c3f5fc484405013817/poetry-0.12.16.tar.gz (154kB)
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
...
Installing build dependencies: started
Installing build dependencies: still running...
Installing build dependencies: finished with status 'error'
ERROR: Complete output from command /usr/local/bin/python /usr/local/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-owlbe57i/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'poetry>=0.12':
ERROR: Collecting poetry>=0.12
Using cached https://files.pythonhosted.org/packages/1f/69/96862c449a3b586c16cdedd97df1c40c94569fec99c3f5fc484405013817/poetry-0.12.16.tar.gz
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
Preparing wheel metadata: started
Preparing wheel metadata: finished with status 'done'
...
Collecting tomlkit<0.6.0,>=0.5.1 (from poetry>=0.12)
Using cached https://files.pythonhosted.org/packages/f7/f7/bbd9213bfe76cb7821c897f9ed74877fd74993b4ca2fe9513eb5a31030f9/tomlkit-0.5.3.tar.gz
ERROR: Exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 178, in main
status = self.run(options, args)
File "/usr/local/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 352, in run
resolver.resolve(requirement_set)
File "/usr/local/lib/python3.6/site-packages/pip/_internal/resolve.py", line 131, in resolve
self._resolve_one(requirement_set, req)
File "/usr/local/lib/python3.6/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
abstract_dist = self._get_abstract_dist_for(req_to_install)
File "/usr/local/lib/python3.6/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
self.require_hashes
File "/usr/local/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 361, in prepare_linked_requirement
with self.req_tracker.track(req):
File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
return next(self.gen)
File "/usr/local/lib/python3.6/site-packages/pip/_internal/req/req_tracker.py", line 94, in track
self.add(req)
File "/usr/local/lib/python3.6/site-packages/pip/_internal/req/req_tracker.py", line 63, in add
% (link, fp.read()))
LookupError: https://files.pythonhosted.org/packages/f7/f7/bbd9213bfe76cb7821c897f9ed74877fd74993b4ca2fe9513eb5a31030f9/tomlkit-0.5.3.tar.gz#sha256=d6506342615d051bc961f70bfcfa3d29b6616cc08a3ddfd4bc24196f16fd4ec2 (from https://pypi.org/simple/tomlkit/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*) is already being built: tomlkit<0.6.0,>=0.5.1 from https://files.pythonhosted.org/packages/f7/f7/bbd9213bfe76cb7821c897f9ed74877fd74993b4ca2fe9513eb5a31030f9/tomlkit-0.5.3.tar.gz#sha256=d6506342615d051bc961f70bfcfa3d29b6616cc08a3ddfd4bc24196f16fd4ec2 (from poetry>=0.12)
----------------------------------------
ERROR: Command "/usr/local/bin/python /usr/local/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-owlbe57i/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'poetry>=0.12'" failed with error code 2 in None
----------------------------------------
ERROR: Command "/usr/local/bin/python /usr/local/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ma_7fsqp/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'poetry>=0.12a3'" failed with error code 1 in None
----------------------------------------
ERROR: Command "/usr/local/bin/python /usr/local/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-thr9o4r9/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'poetry>=0.12'" failed with error code 1 in None
```

**Comment by ob-stripe** [comment] 2019-06-03 16:56
Hey @iamareebjamal, sorry for the trouble here. The switch from pipenv to poetry was released as a patch version since we expected it to have no impact on users.

Apparently that's not the case when building from source though :( I can reproduce this locally with `pip install stripe --no-binary :all:`. I think Alpine cannot use the prebuilt wheels and has to build from source though.

I'll try to see if there's any workaround we can offer, but we might need to revert to using pipenv for the time being.

**Closed** 2019-06-03 23:55 UTC

**Comment by ob-stripe** [comment] 2019-06-04 00:05
This should be fixed in 2.29.4. We're no longer using Poetry, and building from source works again:
```
$ pip install stripe --no-binary :all:
Collecting stripe
  Using cached https://files.pythonhosted.org/packages/2c/16/7bac349457382a15d64d3c88f7070072c4926149f3f9d175735d4b6af009/stripe-2.29.4.tar.gz
Collecting requests>=2.20 (from stripe)
  Using cached https://files.pythonhosted.org/packages/01/62/ddcf76d1d19885e8579acb1b1df26a852b03472c0e46d2b959a714c90608/requests-2.22.0.tar.gz
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.20->stripe)
  Downloading https://files.pythonhosted.org/packages/fc/bb/a5768c230f9ddb03acc9ef3f0d4a3cf93462473795d18e9535498c8f929d/chardet-3.0.4.tar.gz (1.9MB)
     |████████████████████████████████| 1.9MB 4.1MB/s
Collecting idna<2.9,>=2.5 (from requests>=2.20->stripe)
  Downloading https://files.pythonhosted.org/packages/ad/13/eb56951b6f7950cadb579ca166e448ba77f9d24efc03edd7e55fa57d04b7/idna-2.8.tar.gz (174kB)
     |████████████████████████████████| 184kB 15.7MB/s
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests>=2.20->stripe)
  Downloading https://files.pythonhosted.org/packages/4c/13/2386233f7ee40aa8444b47f7463338f3cbdf00c316627558784e3f542f07/urllib3-1.25.3.tar.gz (262kB)
     |████████████████████████████████| 266kB 13.9MB/s
Collecting certifi>=2017.4.17 (from requests>=2.20->stripe)
  Downloading https://files.pythonhosted.org/packages/06/b8/d1ea38513c22e8c906275d135818fee16ad8495985956a9b7e2bb21942a1/certifi-2019.3.9.tar.gz (158kB)
     |████████████████████████████████| 163kB 12.7MB/s
Skipping bdist_wheel for stripe, due to binaries being disabled for it.
Skipping bdist_wheel for requests, due to binaries being disabled for it.
Skipping bdist_wheel for chardet, due to binaries being disabled for it.
Skipping bdist_wheel for idna, due to binaries being disabled for it.
Skipping bdist_wheel for urllib3, due to binaries being disabled for it.
Skipping bdist_wheel for certifi, due to binaries being disabled for it.
Installing collected packages: chardet, idna, urllib3, certifi, requests, stripe
  Running setup.py install for chardet ... done
  Running setup.py install for idna ... done
  Running setup.py install for urllib3 ... done
  Running setup.py install for certifi ... done
  Running setup.py install for requests ... done
  Running setup.py install for stripe ... done
Successfully installed certifi-2019.3.9 chardet-3.0.4 idna-2.8 requests-2.22.0 stripe-2.29.4 urllib3-1.25.3
```
