### ISSUE TITLE
(Network error: A ValueError was raised with error message empty or no certificate, match_hostname needs a SSL socket or SSL context with either CERT_OPTIONAL or CERT_REQUIRED)

### ISSUE THREAD

**Issue by sergueikp** [stripe/stripe-python#1064] opened 2023-09-28 11:35 UTC
### Describe the bug

Hello,
I've installed stripe-5.5.0 on my Linux/Ubuntu OS, and I've got the error message.
When I test it on my windows system everything works fine, the error occurs only on linux.
My Python version is 2.7.12
Requests version: 2.27.1
I've installed last SSL update with: pip install pyOpenSSL
The full error message:
Traceback (most recent call last):
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20151126-py2.7.egg/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20151126-py2.7.egg/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20151126-py2.7.egg/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20151126-py2.7.egg/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20151126-py2.7.egg/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20151126-py2.7.egg/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20151126-py2.7.egg/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20151126-py2.7.egg/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20151126-py2.7.egg/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20151126-py2.7.egg/openerp/api.py", line 256, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20151126-py2.7.egg/openerp/api.py", line 387, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20151126-py2.7.egg/openerp/addons/account_improvement/models/stripe_payment.py", line 35, in action_stripe_payment_link_create
    default_price_data={"unit_amount": 100, "currency": "eur"},
  File "/opt/odoo-8.0-17/python/lib/python2.7/site-packages/stripe-5.5.0-py2.7.egg/stripe/api_resources/abstract/createable_api_resource.py", line 23, in create
    params,
  File "/opt/odoo-8.0-17/python/lib/python2.7/site-packages/stripe-5.5.0-py2.7.egg/stripe/api_resources/abstract/api_resource.py", line 139, in _static_request
    response, api_key = requestor.request(method_, url_, params, headers)
  File "/opt/odoo-8.0-17/python/lib/python2.7/site-packages/stripe-5.5.0-py2.7.egg/stripe/api_requestor.py", line 120, in request
    method.lower(), url, params, headers, is_streaming=False
  File "/opt/odoo-8.0-17/python/lib/python2.7/site-packages/stripe-5.5.0-py2.7.egg/stripe/api_requestor.py", line 367, in request_raw
    method, abs_url, headers, post_data
  File "/opt/odoo-8.0-17/python/lib/python2.7/site-packages/stripe-5.5.0-py2.7.egg/stripe/http_client.py", line 117, in request_with_retries
    method, url, headers, post_data, is_streaming=False
  File "/opt/odoo-8.0-17/python/lib/python2.7/site-packages/stripe-5.5.0-py2.7.egg/stripe/http_client.py", line 171, in _request_with_retries_internal
    raise connection_error
APIConnectionError: Unexpected error communicating with Stripe. It looks like there's
probably a configuration issue locally.  If this problem persists, let
us know at support@stripe.com.

(Network error: A ValueError was raised with error message empty or no certificate, match_hostname needs a SSL socket or SSL context with either CERT_OPTIONAL or CERT_REQUIRED)

### To Reproduce

Install stripe-5.5.0 on linux Ubuntu 20.04
Try to create Product and Price in the stripe API. 

### Expected behavior

My local application has to create the product and price.

### OS

Ubuntu 20.04

### Language version

Python 2.7.12

### Library version

stripe-python-5.5.0

### API version

5.5.0

**Comment by richardm-stripe** [comment] 2023-09-28 19:25
Hello @sergueikp, thanks for the report. I was unable to reproduce this myself in an Ubuntu docker container:

```
# Dockerfile
FROM ubuntu:20.04
RUN apt update && apt install python2 curl -y
RUN curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
RUN python2 get-pip.py
RUN pip install stripe==5.5.0
RUN python -c "import stripe; stripe.api_key = "sk_test_xyz"; stripe.Customer.list()"
```

```shell
$ docker build . -t blah
$ docker run blah
# Successfully makes a request to Stripe as expected
```

Judging by the error message, I don't think this is a problem we can fix in stripe-python and the cause probably lies elsewhere in your environment.

Do you have a minimal reproduction? What other libraries are you importing? I found [an issue on a different repo](https://github.com/eventlet/eventlet/issues/226) where this error message appeared, where merely *importing* a library could cause `requests` to start failing.

Some debugging suggestions:
- Instead of using `stripe-python`, could you try making an https request to `api.stripe.com` directly using `requests`? If this succeeds then that would implicate stripe-python.
- You might try running
```
import ssl
import socket
HOSTNAME = 'api.stripe.com'
context = ssl.create_default_context()
sock = socket.create_connection((HOSTNAME, 443))
ssl_sock = context.wrap_socket(sock, server_hostname=HOSTNAME)
cert = ssl_sock.getpeercert()
print(cert)
ssl_sock.close()
```
in Python on your server. I'm pretty sure the error you are seeing is related to `ssl_sock.getpeercert()` failing to return certificate information. If it fails when you have only imported `ssl` and `socket`, then that indicates that there's something very wrong with the python SSL setup on your server that has nothing to do with any libraries you are using. If it succeeds when you have only imported `ssl` and `socket`, but begins to fail when you start importing more libraries, that can help you find the culprit.

Anyway, hope this helps. You might consider contacting Stripe support at https://support.stripe.com/contact for more interactive help, since this seems to be more of an integration issue than a problem with stripe-python itself.

**Comment by richardm-stripe** [comment] 2023-09-29 23:12
I'm pre-emptively closing this issue, as I do not think it represents an active issue with stripe-python and is more of an integration help issue. Feel free to comment/re-open if you are able to provide a minimal reproduction that narrows the problem down to stripe-python.

**Closed by richardm-stripe** 2023-09-29 23:12 UTC
Labels: bug
