### ISSUE TITLE
Testing subscription trial periods with trial_end in near future raises InvalidRequestError

### ISSUE THREAD

**Issue by rasmus-hvid** [stripe/stripe-python#679] opened 2020-09-15 13:34 UTC
According to the [docs](https://stripe.com/docs/billing/testing#trials) the recommended way to test subscription trial periods is to set the trial_end a few minutes in the future:

> "You can test how your integration handles trial periods without waiting a full trial period to see the results by creating a new subscription with a trial_end value a few minutes in the future."

However, when I do this the following exception is raised: 
```
 stripe.error.InvalidRequestError: Request req_AbdZk5IccnHSXH: The `trial_end` date has to be at least 2 days in the future.
```

According to the [docs](https://stripe.com/docs/api/checkout/sessions/create) this is the correct behavior in live mode, but since I am running in test mode, this seems to be a mistake.

I am using Stripe Checkout and I create the Checkout session by invoking the following function:

```python
session = stripe.checkout.Session.create(
    customer=user.customer_id,
    payment_method_types=["card"],
    line_items=[
        {
            "price": "price_1HHQt1L7xekzMs4akL5XUO7N",
            "quantity": 1,
        }
    ],
    mode="subscription",
    success_url="https://localhost:3000/success",
    cancel_url="https://localhost:3000/cancel",
    subscription_data={"trial_end": int(datetime.now().timestamp()) + 120},
)

```

**Comment by karlr-stripe** [comment] 2020-09-15 14:30
Hi there! This is not a bug with the stripe-python library itself so I'm going to close this out — I'd suggest following up with our support team at https://support.stripe.com/email for questions about using the API and products.

In this case, it's because Checkout itself does not support trial periods less than two days in the future. If you create the subscription directly using `stripe.Subscriptions.create` for example, the trial period can be set a few seconds/minutes into the future as the docs describe, but that's not supported by Checkout (for example, because a CheckoutSession is a payment page that lasts for 24 hours, it might be complicated to handle if the specified `trial_end` time is passed _while_ the customer is on the page filling out their details, so you can see why this might not be supported). This is not related at all to live/test mode, it's the same in both and is a detail of Checkout itself.

**Closed by karlr-stripe** 2020-09-15 14:30 UTC
