### ISSUE TITLE
Customer.list_payment_methods with auto_paging_iter does not respect initial parameters

### ISSUE THREAD

**Issue by AndreasHogstrom** [stripe/stripe-python#755] opened 2021-12-20 16:25 UTC
Similarly to this old issue; https://github.com/stripe/stripe-python/issues/221 , the `Customer.list_payment_methods` used in conjunction with `auto_paging_iter` does not persist any parameters when going to the next page.

Python version: 3.9.7
Stripe SDK version: 2.63.0

Example:
Both the `type` parameter and the customer ID is lost:
```python
# Generated URL: /v1/customers/cus_123/payment_methods?type=card
payment_methods = stripe.Customer.list_payment_methods("cus_123", type="card")

# Next page generated URL: /v1/customers/:customer/payment_methods?starting_after=pm_123
for payment_method in payment_methods.auto_paging_iter():
    pass
```

**Comment by dcr-stripe** [comment] 2021-12-20 18:27
Thanks for the report @AndreasHogstrom - I can reproduce this as well. The team is looking into fixing this and will report back.

**Comment by dcr-stripe** [comment] 2021-12-21 16:10
Fixes have been merged for this to pass the parameters forward. Thanks again for the report - great find.

 Unfortunately there still remains an issue with the `/payment_methods` endpoint where it returns `/v1/customers/:customer/payment_methods` in the `url` field instead of `/v1/customers/cus_123/payment_methods`. This will need to be fixed independently.

I'll keep this issue open until we've released a version of stripe-python with these fixes.

**Comment by dcr-stripe** [comment] 2021-12-21 18:59
https://github.com/stripe/stripe-python/releases/tag/v2.64.0 has been released including this fix.

As I mentioned, the `/payment_methods` endpoint is still experiencing a bug, but that is being worked on independently from the SDKs.

I'll close this issue since the initial parameters are now being respected, but I'll make sure to update here as well once the `/payment_methods` bug is fixed.

**Closed by dcr-stripe** 2021-12-21 18:59 UTC
