### ISSUE TITLE
stripe.Invoice.auto_paging_iter can infinite loop

### ISSUE THREAD

**Issue by timvisher** [stripe/stripe-python#567] opened 2019-05-09 13:39 UTC
Python version: Python 3.5.2
virtualenv:
```
Package           Version    Location
----------------- ---------- -----------------------
astroid           2.1.0
backcall          0.1.0
backoff           1.3.2
certifi           2018.11.29
chardet           3.0.4
decorator         4.3.2
idna              2.8
ipdb              0.11
ipython           7.3.0
ipython-genutils  0.2.0
isort             4.3.10
jedi              0.13.3
jsonschema        2.6.0
lazy-object-proxy 1.3.1
mccabe            0.6.1
parso             0.3.4
pexpect           4.6.0
pickleshare       0.7.5
pip               19.1.1
pkg-resources     0.0.0
prompt-toolkit    2.0.9
ptyprocess        0.6.0
Pygments          2.3.1
pylint            2.1.1
python-dateutil   2.8.0
pytz              2018.4
requests          2.21.0
setuptools        41.0.1
simplejson        3.11.1
singer-python     5.5.0      /opt/code/singer-python
six               1.12.0
stripe            2.10.1
tap-stripe        1.2.4
traitlets         4.3.2
typed-ast         1.3.1
urllib3           1.24.1
wcwidth           0.1.7
wrapt             1.11.1
```

I'm happy to provide a direct reproduction case via a more secure channel if you need it.

I am one of the maintainers of the [singer.io's][1] [stripe tap][2] and we've encountered an issue with one of our customers where they are infinitely looping over a particular Invoice's line items.

[1]: https://www.singer.io/
[2]: https://github.com/singer-io/tap-stripe

We call `<Invoice instance>.lines.auto_paging_iter()` ([here][5] using `.lines` as the `object_list` and [here][3] calling `auto_paging_iter()` on the `object_list`) for [each `Invoice`][4]

[3]: https://github.com/singer-io/tap-stripe/blob/f5c70d09a458bed8a9be711396ddccea5c5dcd35/tap_stripe/__init__.py#L497-L498
[5]: https://github.com/singer-io/tap-stripe/blob/f5c70d09a458bed8a9be711396ddccea5c5dcd35/tap_stripe/__init__.py#L511-L512
[4]: https://github.com/singer-io/tap-stripe/blob/f5c70d09a458bed8a9be711396ddccea5c5dcd35/tap_stripe/__init__.py#L464

You can see from the following ipdb log the infinite loop:

```
ipdb> pprint([x.id for x in itertools.islice(parent_obj.lines.auto_paging_iter(), 50)])
INFO message='Request to Stripe api' method=get path=https://api.stripe.com/v1/invoices/in_BPw<redacted>SYz/lines?starting_after=sub_B95<redacted>Cn9
INFO message='Stripe API response' path=https://api.stripe.com/v1/invoices/in_BPw<redacted>SYz/lines?starting_after=sub_B95<redacted>Cn9
INFO message='Request to Stripe api' method=get path=https://api.stripe.com/v1/invoices/in_BPw<redacted>SYz/lines?starting_after=sub_B95<redacted>Cn9
INFO message='Stripe API response' path=https://api.stripe.com/v1/invoices/in_BPw<redacted>SYz/lines?starting_after=sub_B95<redacted>Cn9
INFO message='Request to Stripe api' method=get path=https://api.stripe.com/v1/invoices/in_BPw<redacted>SYz/lines?starting_after=sub_B95<redacted>Cn9
INFO message='Stripe API response' path=https://api.stripe.com/v1/invoices/in_BPw<redacted>SYz/lines?starting_after=sub_B95<redacted>Cn9
INFO message='Request to Stripe api' method=get path=https://api.stripe.com/v1/invoices/in_BPw<redacted>SYz/lines?starting_after=sub_B95<redacted>Cn9
INFO message='Stripe API response' path=https://api.stripe.com/v1/invoices/in_BPw<redacted>SYz/lines?starting_after=sub_B95<redacted>Cn9
```

Obviously, I would expect `auto_paging_iter` not to infinite loop, although I'm not sure whether this indicates a problem in the actual data returned or a problem in the `auto_paging_iter` implementation.

Happy to provide further details if you need it.

**Comment by timvisher** [comment] 2019-05-09 15:37
I believe in this instance the problem is actually with the API, as I can easily reproduce this from `curl`.

Notably, the API version is `2018-09-24`.

Here's a detailed repro script that does not use the SDK. https://gist.github.com/timvisher/0119417599ac51a0500f2b92dcaeea91

**Comment by remi-stripe** [comment] 2019-05-09 15:42
@timvisher To debug this, will likely need to look at the raw data in the account but since the ids are redacted (which was definitely a good idea for a public link) we can't find the information.

Would you be able to reach out to our support team with the exact subscription id so that they can investigate further?

I'll close this one out since it's not a bug with the library and seems more like an edge-case with the API that is not handled well but make sure to link to it in your email and mention my name!

**Closed by remi-stripe** 2019-05-09 15:42 UTC

**Comment by timvisher** [comment] 2019-05-09 18:06
I would still call this a bug with the library in that it's not handling this edge case with the API. Preferably I wouldn't have to write work around code on my end in order to handle this case. That said I'll definitely reach out to support with more details.

**Comment by remi-stripe** [comment] 2019-05-09 18:13
That's fair but the library here is doing the right thing by continuing to paginate. The API is not returning the right information if you get the same page more than once, or at least the same "last id"
