### ISSUE TITLE
Minimum charge currency issue

### ISSUE THREAD

**Issue by kumarStoryboard** [stripe/stripe-python#643] opened 2020-02-12 11:03 UTC
python: Python 3.6.5 (default, Jul 26 2018, 23:29:40)
stripe==2.10.1

We are having a issue while charging $0.50 USD . As this is the minimum amount one has to charge according to stripe docs to make a succesful minimum payment.

But while charging it we are facing a error from your stripe as:

attached in the image here as heighlighted in console:
https://user-images.githubusercontent.com/24431309/74328846-a8d1df80-4db4-11ea-9a38-b9e31d1b739c.png

![Screenshot 2020-02-07 at 6 07 07 PM](https://user-images.githubusercontent.com/24431309/74328846-a8d1df80-4db4-11ea-9a38-b9e31d1b739c.png)
So why is my charge getting converted from USD to EUROS even if I pass the 
param to stripe  using this function from stripe library
```
stripe.Charge.create(
                    amount=<your amount>,
                    currency="USD",
                    customer=card.stripe_cus_id,
                    description="xyz"
                )
```

**Comment by remi-stripe** [comment] 2020-02-12 15:48
@kumarStoryboard I'm going to close this issue as this is not a bug with the library itself and instead it's a product question. I recommend reaching out to our support team instead for product questions and you can contact them here: https://support.stripe.com/contact

To unblock you though the minimum you can charge is based on your payout currency after conversion. $0.50 USD is the minimum in the US, but if you're in France for example and your default currency is euro, then the minimum amount you can charge in USD is such that after conversion you have at least 0.50€. This is covered in details [here](https://stripe.com/docs/currencies#minimum-and-maximum-charge-amounts) below the table:

> Of you only have one bank account in use and you create charges in the same currency as it, the minimum amount is simply what is listed for your currency. Charges that must be converted into your account’s default settlement currency must meet the equivalent minimum of the settlement currency.

**Closed by remi-stripe** 2020-02-12 15:48 UTC

**Comment by kumarStoryboard** [comment] 2020-02-13 10:11
thanks for helping out
