### ISSUE TITLE
latest stripe version doesn't work with python3.5 I can't install it.

### ISSUE THREAD

**Issue by Ambitiont109** [stripe/stripe-python#716] opened 2021-03-12 07:05 UTC
I was going to install a stripe with pip3 on python3.5.
However, It gets an error while we are installing it.
![imgpsh_fullsize_anim (2)](https://user-images.githubusercontent.com/45891661/110904731-32b9e800-82e8-11eb-898e-57c3af06a747.png)

**Comment by Ambitiont109** [comment] 2021-03-12 07:07
May I know which stripe version do we have to use for python 3.5?
Best regards.

**Comment by remi-stripe** [comment] 2021-03-12 23:08
@Ambitiont109 The error here doesn't seem specific to Stripe and seems to file in `site-packages`. Have you been able to install other libraries with pip before? Googling around it seems to be more a python/pip mis-configuration here such as [this issue](https://github.com/pypa/setuptools/issues/2541).

**Comment by Ambitiont109** [comment] 2021-03-13 00:05
Yes. Other packages were installed well. However, on stripe, It didn't work.
In my opinion, it is because of the'' string placeholder. I know as it is supported from Python 3.6.
Since we are using Python 3.5, we get an error while installing the stripe module.
Best regards.

**Comment by remi-stripe** [comment] 2021-03-13 02:11
can you say more about what you mean by ` the'' string placeholder`? I'm confused by what in this error stack indicates an issue with stripe-python itself. I'm definitely trying to investigate further and help unblock but I'm not following what the problem is and the installation locally for me with that python 3.5.10 for example.

**Comment by Ambitiont109** [comment] 2021-03-13 02:37
Okay. I see

**Comment by pquentin** [comment] 2021-09-07 19:40
The traceback is entirely in pip. They stopped supporting Python 3.5 in pip 21.0: https://pip.pypa.io/en/stable/news/#v21-0. They started using f-strings, which are syntax errors on Python 3.5. You could use an earlier pip version, but I'd advise migrating to Python 3.6 or later, as Python 3.5 isn't supported anymore.

**Comment by SteveHere** [comment] 2021-09-08 02:44
I concur @pquentin's comment: F-strings were added in Python 3.6, so it makes sense that you would encounter a syntax error in 3.5. The only way around this is to install a newer version of Python, unfortunately. However, you should see some performance improvements by just updating to the latest version of Python.

**Comment by richardm-stripe** [comment] 2022-01-18 20:27
Closing, as this is not an issue with stripe-python directly (and is quite old).

**Closed by richardm-stripe** 2022-01-18 20:27 UTC
