### ISSUE TITLE
Wheel dependencies on python3

### ISSUE THREAD

**Issue by ningirsu** [stripe/stripe-python#400] opened 2018-02-27 13:06 UTC
Hello!

Since the build was compiled using python2.7, it seems that it breaks the conditional dependencies here `https://github.com/stripe/stripe-python/blob/master/setup.py#L36`

So for instance, when installing stripe on python3, we now have a dependency on `simplejson`

One easy fix is to use https://www.python.org/dev/peps/pep-0508/ to manage conditional dependencies.

thks!

**Comment by ob-stripe** [comment] 2018-02-27 14:01
Hi @ningirsu, good catch! I recently tweaked the build process to generate a single universal wheel, but failed to realize that this would include unnecessary dependencies in Python 3 environments.

Using PEP 508 is indubitably the right thing to do here. My only concern is that support for PEP 508 was introduced relatively recently in pip ([8.1.2](https://pip.pypa.io/en/stable/news/)) -- I'm not entirely sure what happens on older pip versions.

Regarding `simplejson` specifically, I think we can simply drop the requirement entirely. AFAIK it was only a requirement on Python <= 2.5 and 3.0, both of which have not been supported in a long time. All supported Python versions should be able to use the standard library's `json` module.

@brandur-stripe wdyt?

**Comment by brandur-stripe** [comment] 2018-02-27 16:13
@ningirsu Sorry about the trouble here, and thanks for adding the helpful remediation advice!

> Regarding simplejson specifically, I think we can simply drop the requirement entirely. AFAIK it was only a requirement on Python <= 2.5 and 3.0, both of which have not been supported in a long time. All supported Python versions should be able to use the standard library's json module.

@ob-stripe +1 your assessment. 2.5's been deprecated since mid-2013 and it's time to move on. 2.6 and 2.7 both have a built-in `json` package, so it should be safe to drop `simplejson` completely.

I noticed that we have one more conditional check in `setup.py` on Python < `2.6` so that we can constrain `requests` and pull in `ssl`. Since again this is in place for 2.5, I think it's safe to drop this completely as well.

I'm on run this week so I can put a PR together.

**Comment by brandur-stripe** [comment] 2018-02-27 16:16
@ningirsu And actually, your PR is so close to what we'd want anyway that if you want to tweak it a little bit, we can pull it in instead of one that I make.

Do you want to just drop the conditional dependencies in favor of the original `install_requires=install_requires`? Also, while you're at it maybe remove the Python 2.5 deprecation warning. For the same reason the universal wheel doesn't handle the original conditionals properly, I don't think this will trigger how it was intended to.

Thanks again!

**Comment by ningirsu** [comment] 2018-02-27 16:27
@brandur-stripe Yep Sure! Just updated the PR

**Comment by ob-stripe** [comment] 2018-02-27 17:59
Fixed in 1.79.1. Thanks again for the report and the fix @ningirsu!

**Closed by ob-stripe** 2018-02-27 17:59 UTC

**Comment by ningirsu** [comment] 2018-02-27 22:33
Thanks to you for handling this so quickly!
I will now be able to revert my hotfix on the Sqreen backend :)
