### ISSUE TITLE
json.dumps Fails when no indent option is provided

### ISSUE THREAD

**Issue by vcatalano** [stripe/stripe-python#220] opened 2016-04-05 00:30 UTC
Calling `json.dumps` on a Customer object causes a TypeError when no `indent` option is provided. This is strange since the call does not raise an exception when an indent value _is_ provided. Here's an example:

```python
    import json

    stripe.Charge.create(...)

    # Works!
    customer_json = json.dumps(dict(customer), indent=2)

    # Raises `TypeError`
    customer_json = json.dumps(dict(customer))
```

I'm currently using Python 2.7.11, however, this may be an issue with the json library.

**Comment by brandur** [comment] 2016-04-05 01:22
Weird!

I think we'll need a little more information on this one though. Is there a stack trace? Error message?

**Comment by olivierbellone** [comment] 2016-04-11 20:12
This is a weird one indeed!

It seems to be due to the fact that when no `indent` parameter is passed, the `json` module will [try to use its C encoder](https://github.com/python/cpython/blob/7c2fcc5c607f0ae22a8b0d77aeb98ca2fc7a760b/Lib/json/encoder.py#L246-L256) rather than its pure Python encoder.

For some reason, the C encoder trips when trying to encode our `ListObject`s:
```python
>>> lo = stripe.resource.ListObject.construct_from(
            {'object': 'list', 'data': [{'id': 'foo'}]},
            'mykey'
        )
>>> lo
<ListObject list at 0x103ca7178> JSON: {
  "data": [
    {
      "id": "foo"
    }
  ], 
  "object": "list"
}
>>> json.dumps(lo)

Traceback (most recent call last):
  File "<pyshell#188>", line 1, in <module>
    json.dumps(lo)
  File "/Users/ob/.pyenv/versions/2.7.11/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/Users/ob/.pyenv/versions/2.7.11/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/ob/.pyenv/versions/2.7.11/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be a string
```
even though both keys are strings, and it's perfectly capable of encoding both values:
```python
>>> [type(k) for k in lo.keys()]
[<type 'str'>, <type 'str'>]
>>> json.dumps(lo['object'])
'"list"'
>>> json.dumps(lo['data'])
'[{"id": "foo"}]'
```

I cannot think of a simple way to fix this on our end. The workaround is pretty simple, just pass an `indent` parameter. Alternatively, it's possible to kill the C encoder:
```python
import json
json.encoder.c_make_encoder = None
```

Note that if you can live with `indent=2` and `sort_keys=True`, it's much simpler and cleaner to use the built-in JSON encoding, e.g. `str(customer)`.

**Comment by olivierbellone** [comment] 2016-04-11 20:41
Dug a little bit more. IMHO, it's more of a bug in Python's JSON encoder:
```python
>>> class Foo(dict):
	def __iter__(self):
		return self.get('data', []).__iter__()

>>> a = Foo({'data': [{'a': 'b'}]})
>>> a
{'data': [{'a': 'b'}]}
>>> for i in a:
	print i

{'a': 'b'}
>>> json.dumps(a)

Traceback (most recent call last):
  File "<pyshell#47>", line 1, in <module>
    json.dumps(a)
  File "/Users/ob/.pyenv/versions/2.7.11/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/Users/ob/.pyenv/versions/2.7.11/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/ob/.pyenv/versions/2.7.11/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be a string
```

**Comment by olivierbellone** [comment] 2016-04-12 22:02
@brandur Considering the above, I think we can close this issue.

**Comment by brandur** [comment] 2016-04-12 22:07
Thanks for digging into this one @olivierbellone!

> Considering the above, I think we can close this issue.

+1. It would be nice to fix it, but it doesn't really seem to be too common of a case, and at least we do have that workaround to suggest. Closing it out.

**Closed by brandur** 2016-04-12 22:07 UTC

**Comment by arkilis** [comment] 2016-06-11 09:23
most of the severs are still using Python 2.7.6 as the default. Strongly recommend to let users know about this issue.

**Comment by jbg** [comment] 2017-01-12 13:48
This is not a bug in Python's JSON encoder.

Overriding `__iter__` on a `dict` subclass to return something other than an iterator over its keys makes the subclass incompatible with `dict`. Iterating a `dict` returns its keys.

**Comment by ob-stripe** [comment] 2017-01-12 15:38
The fact `json.dumps` produces different results depending on whether it uses its internal C implementation or Python implementation (which is clearly something that users of the `json` module shouldn't care or even know about) is clearly a bug (imho).

That said, I don't disagree that the way we subclass `dict` for our `ListObject`s is unorthodox and a little bit awkward, but aside from this very specific issue it seems to work fine.
