### ISSUE TITLE
Passing a wildcard type to Event.list creates an error

### ISSUE THREAD

**Issue by michael-erasmus** [stripe/stripe-python#358] opened 2017-10-25 23:56 UTC
I'm trying to use the `Event.list` method to get a subset of events based on their type

According to the Stripe [Api docs](https://stripe.com/docs/api/python#list_events-type):

```
type
optional
A string containing a specific event name, or group of events using * as a wildcard. The list will be filtered to include only events with a matching event property.
```

I tried the following:

```python
stripe.Event.list(type='customer.subscription.*')
```

That seems to trigger a http 500 error on the server:

```
INFO:stripe:GET https://api.stripe.com/v1/events?type=customer.subscription.%2A 500


/opt/conda/lib/python3.6/site-packages/stripe/api_requestor.py in handle_api_error(self, rbody, rcode, resp, rheaders)
    166         else:
    167             raise error.APIError(err.get('message'), rbody, rcode, resp,
--> 168                                  rheaders)
    169 
    170     def request_raw(self, method, url, params=None, supplied_headers=None):

APIError: Request req_GuNqYP3ul412Nh: An unknown error occurred
```

It seems like perhaps the url param is being incorrectly encoded. Any way to get around this?

**Comment by ob-stripe** [comment] 2017-10-26 09:47
Hi @michael-erasmus. I am unable to reproduce this on my end. Using the latest stripe-python (1.70.0):

```python
>>> stripe.Event.list(type='customer.subscription.*')
<ListObject list at 0x104474be0> JSON: {
  "data": [
    {
       ...
    }
  ],
  "has_more": true,
  "object": "list",
  "url": "/v1/events"
}
```

I suspect this is not a problem with the Python library, but rather an issue specific to your own account on the API's end. Can you please send a message using the form at https://support.stripe.com/email to report this problem? This way we will be able to look at your account's logs and clarify what's happening.

I'm closing the issue for now, but will reopen if it is indeed a problem with the Python library.

**Closed by ob-stripe** 2017-10-26 09:47 UTC

**Comment by michael-erasmus** [comment] 2017-10-26 15:55
Thanks @ob-stripe, good to know it's only on my end then! I'll reach out to support to try and get to the bottom of it. Great work on this project btw, the API is so well designed!

**Comment by davidgasquez** [comment] 2017-10-26 16:04
Hey @ob-stripe! We found that adding the `created` filter makes the query work.

```
stripe.Event.list(created=range, type='customer.subscription.*', limit=100)
```

Not sure why the other query doesn't work for us. 🤔 We'll keep reporting if we find something else!

**Comment by ob-stripe** [comment] 2017-10-26 21:42
@michael-erasmus @davidgasquez I looked up your original query using the request ID mentioned in the error message, and it looks like the request timed out on the API's end.

This of course shouldn't happen, but it's not an issue with the Python library -- the parameters are correctly encoded by the library and decoded on the API's end. If you write to support using the contact form, we'll be able to take a closer look and tell you if it was just a transient error or if there's something else going on.

Sorry for the inconvenience, and thanks for your kind words about the API!
