### ISSUE TITLE
metadata boolean types are not perserved

### ISSUE THREAD

**Issue by polski-g** [stripe/stripe-python#434] opened 2018-06-10 16:34 UTC
Using version stripe==1.82.1 on Python 3.6.5.

Create a Stripe object via the Python API, lets say a Customer with custom metadata of `{"something": True}` (notice the type is bool). But when you fetch it with `stripe.Customer.retrieve()`, you get `{"something": "True"}` (now the type is str).

I can monkey-patch this with the code below, but just an FYI.

```python
from stripe.stripe_response import StripeResponse
import json


class MyDecoder(json.JSONDecoder):
    def __init__(self, *args, **kwargs):
        json.JSONDecoder.__init__(self, object_hook=self.object_hook, *args, **kwargs)

    def object_hook(self, obj):
        if isinstance(obj, dict) and 'metadata' in obj:
            for k,v in obj['metadata'].items():
                if v == 'True':
                    obj['metadata'][k] = True
                elif v == 'False':
                    obj['metadata'][k] = False
        return obj


def stripe_response__init__(self, body, code, headers):
    self.body = body
    self.code = code
    self.headers = headers
    self.data = json.loads(body, cls=MyDecoder)
StripeResponse.__init__ = stripe_response__init__

```

**Comment by ob-stripe** [comment] 2018-06-11 08:32
Hi @polski-g, thanks for the report!

Metadata in Stripe's API maps strings to strings, so it is expected that when you retrieve a resource from the API, all metadata values are strings.

The issue here is more that non-string values are accepted when _setting_ metadata. However, the Python library does not enforce types when setting parameters (in fact, it knows nothing at all about parameters). Because of URL-encoding, all values are encoded as "strings", and it's the API that does the type validation. In the case of metadata, the API expects strings, so `'true'` or `'false'` are valid values.

Closing the issue since this is not a bug (aside from the much larger issue of the library not enforcing types on request parameters, which I don't think we'll be able to tackle soon), but feel free to reply if you have more questions.

**Closed by ob-stripe** 2018-06-11 08:32 UTC
