### ISSUE TITLE
Create customer with currency parameter issue

### ISSUE THREAD

**Issue by sdklab007** [stripe/stripe-python#680] opened 2020-09-27 08:58 UTC
**version:** 2.35.1

Passing currency in the create customer throws an error. 
While I am sure, we can create a customer with the default currency from the dashboard, I am unable to do the same via Stripe Python SDK.

```
customer = stripe.Customer.create(
    currency="inr",
    email=kwargs.get('email'),
    name=kwargs.get('business_name') if bool(kwargs.get('business_name')) else kwargs.get('user_full_name'),
    address={
        "city": kwargs.get('city'),
        "country": kwargs.get('country_code'),
        "line1": kwargs.get('address'),
        "line2": "",
        "postal_code": kwargs.get('zipcode'),
        "state": kwargs.get('city'),
    },
)
```
**Error:**
stripe.error.InvalidRequestError: Request req_XHaA4oBWun1WiX: Received unknown parameter: currency

**Comment by remi-stripe** [comment] 2020-09-27 17:53
@sdklab007 The `currency` parameter does not exist on customer creation so this is not something you can (or should) pass. 
I'm going to close this out as it's not a bug with the library but don't hesitate to follow up with our support team for more information: https://support.stripe.com/contact

**Closed by remi-stripe** 2020-09-27 17:53 UTC
