### ISSUE TITLE
Invalid boolean: True

### ISSUE THREAD

**Issue by kaduev13** [stripe/stripe-python#487] opened 2018-10-25 11:08 UTC
Hi! Starting from today morning I faced a lot of exceptions from stripe API.

The simplest way to reproduce the issue is:
```python3
...
invoice = stripe.Invoice.retrieve('some_invoice_id')
invoice.closed = True
invoice.save()
```

It results as an exception:

```
In [25]: invoice.save()
[25/Oct/2018 12:56:15] INFO [stripe:62] message='Request to Stripe api' method=post path=https://api.stripe.com/v1/invoices/XXX
[25/Oct/2018 12:56:16] INFO [stripe:62] message='Stripe API response' path=https://api.stripe.com/v1/invoices/XXX response_code=400
[25/Oct/2018 12:56:16] INFO [stripe:62] error_code=None error_message='Invalid boolean: True' error_param=closed error_type=invalid_request_error message='Stripe API error received'
---------------------------------------------------------------------------
InvalidRequestError                       Traceback (most recent call last)
<ipython-input-25-5b9a97d7c813> in <module>()
----> 1 invoice.save()

~/.virtualenvs/project/lib/python3.6/site-packages/stripe/api_resources/abstract/updateable_api_resource.py in save(self, idempotency_key)
     30         if updated_params:
     31             self.refresh_from(self.request('post', self.instance_url(),
---> 32                                            updated_params, headers))
     33         else:
     34             util.logger.debug("Trying to save already saved object %r", self)

~/.virtualenvs/project/lib/python3.6/site-packages/stripe/stripe_object.py in request(self, method, url, params, headers)
    205             key=self.api_key, api_base=self.api_base(),
    206             api_version=self.stripe_version, account=self.stripe_account)
--> 207         response, api_key = requestor.request(method, url, params, headers)
    208 
    209         return util.convert_to_stripe_object(response, api_key,

~/.virtualenvs/project/lib/python3.6/site-packages/stripe/api_requestor.py in request(self, method, url, params, headers)
     92         rbody, rcode, rheaders, my_api_key = self.request_raw(
     93             method.lower(), url, params, headers)
---> 94         resp = self.interpret_response(rbody, rcode, rheaders)
     95         return resp, my_api_key
     96 

~/.virtualenvs/project/lib/python3.6/site-packages/stripe/api_requestor.py in interpret_response(self, rbody, rcode, rheaders)
    304                 rbody, rcode, rheaders)
    305         if not (200 <= rcode < 300):
--> 306             self.handle_error_response(rbody, rcode, resp.data, rheaders)
    307 
    308         return resp

~/.virtualenvs/project/lib/python3.6/site-packages/stripe/api_requestor.py in handle_error_response(self, rbody, rcode, resp, rheaders)
    117                 rbody, rcode, resp, rheaders, error_data)
    118 
--> 119         raise err
    120 
    121     def specific_api_error(self, rbody, rcode, resp, rheaders, error_data):

InvalidRequestError: Request req_YYY: Invalid boolean: True
```

But, if I use `invoice.closed = 'true'` instead of `invoice.closed = True` it works. There were no such problem before, probably, something was changed on the Stripe side (but I can't find any new release updates). Looks like `'True'` and `'False'` values are not accepted by Stripe anymore. 

Python version: 3.6.6
Stripe api version: 2018-09-24
stripe-python version: 2.4.0

**Comment by ob-stripe** [comment] 2018-10-25 11:40
Hi @kaduev13, thanks for the report. I've confirmed this is a backend issue and will be fixed ASAP. I'll update here when it's fixed.

**Comment by kaduev13** [comment] 2018-10-25 11:43
@ob-stripe thank you so much, it'll help a lot 👍

**Comment by ob-stripe** [comment] 2018-10-25 12:31
@kaduev13 The issue has been fixed and you can safely retry those requests. Apologies for the inconvenience!

I'm closing this GitHub issue since there's no action required on the library's end. If you have followup questions, please reach reach out to support at https://support.stripe.com/email.

**Closed by ob-stripe** 2018-10-25 12:31 UTC
