### ISSUE TITLE
Support for listing Payouts intitiated after a Transfer

### ISSUE THREAD

**Issue by leokhachatorians** [stripe/stripe-python#633] opened 2019-12-04 18:45 UTC
Not sure if its a bug, feature request, or something that is currently working as intended.

I'm currently playing around with the StripeConnect platform and noticed that if I initiate a Transfer, I have no way of programmatically fetching the status of Payouts for that account I transferred too. The accounts I'm transferring to are Stripe Connect Custom accounts and as such they don't have access to a dashboard (I'm pretty sure at least?)

I can however in my Admin dashboard see the status of the Payout(s) in question though. 

Attempting to call `stripe.Payout.retrieve('id_of_payout')` results in an invalid request stating that Payout doesn't exist.

**Comment by remi-stripe** [comment] 2019-12-04 19:03
@leokhachatorians This is not a bug with the library and so I'm going to close this issue. It's more a question on how to use the API and I'd recommend talking to our support team instead https://support.stripe.com/contact

Just to unblock you: the payouts are on the connected account, so when you make API requests on their behalf you need to tell Stripe. This is done by passing the connected account id in the call as documented here: https://stripe.com/docs/connect/authentication#authentication-via-the-stripe-account-header

**Closed by remi-stripe** 2019-12-04 19:03 UTC

**Comment by leokhachatorians** [comment] 2019-12-04 19:07
Ah I see. Thanks for your help.
