### ISSUE TITLE
Bug when using card token in source.create()

### ISSUE THREAD

**Issue by luxcem** [stripe/stripe-python#446] opened 2018-07-12 12:52 UTC
stripe==1.84.1
python==3.6.4

[The documentation on Testing](https://stripe.com/docs/testing) does not explain how to test Sources. But when using a card token (for example "tok_visa") like: 
```python
customer = stripe.Customer.retrieve("cus_aaaaaa")
customer.sources.create(source="tok_visa)
```
The SDK raises those errors: 

```
    def __getitem__(self, k):
        try:
>           return super(StripeObject, self).__getitem__(k)
E           KeyError: 'card'

lib/python3.6/site-packages/stripe/stripe_object.py:118: KeyError
```

The documentation should provide testing Source tokens and the sdk should handle those errors.

**Comment by remi-stripe** [comment] 2018-07-12 14:07
@luxcem I tried to reproduce on that exact version but I do not get any error. I can directly add a card to a customer via the token as expected. Would you have a bit more details about the issue and what is causing the crash?

**Comment by ob-stripe** [comment] 2018-07-23 13:01
Since we were unable to reproduce the issue and no further details were provided, I'm closing the issue.

@luxcem Feel free to reply with more information if you're still seeing this issue and we'll reopen.

**Closed by ob-stripe** 2018-07-23 13:01 UTC
