### ISSUE TITLE
"Missing required param" on update for nested objects

### ISSUE THREAD

**Issue by gsakkis** [stripe/stripe-python#255] opened 2016-10-12 18:58 UTC
It seems like required parameters for nested objects are required not just for creation but for update as well, contradicting "any parameters not provided will be left unchanged" mentioned in the docs. This happens when trying to update for example `customer.shipping.address` without also setting `customer.shipping.name`.

**Comment by brandur** [comment] 2016-10-13 00:24
So I don't want to be too technical on this, but the argument could be made that the current language is correct: both of the fields you cited are part of the same parameter ("customer"), and therefore the current statement could be considered self-consistent, even if not universally illuminating.

I played around with a few other wordings (e.g. 'Updates the specified charge by setting the values of the parameters passed. Any parameters not provided will be left unchanged except when updating subresources, where all fields must be specified.') but I suspect that adding more prose here will lead to more confusion rather than less.

I'm going to close this out given that it's not a bug on the bindings, but if you have any particular ideas on how we could offer more clarity, let me know.

**Closed by brandur** 2016-10-13 00:24 UTC

**Comment by gsakkis** [comment] 2016-10-13 05:45
I'm surprised and disappointed that the current behaviour is not considered a bug, so even if wording is improved to clarify it that's hardly a win. I have to resort to some ugly brittle code to work around the issue on my end just to handle the `customer.shipping` updates; I'll have to remember to do the same for any nested object I may need to update in the future. 

What makes the workaround worse is that I have to sidestep a related issue that results in changing `None` values to empty strings, which I traced it back to `stripe.resource._compute_diff` (`return current if current is not None else ""`). I guess there must be a reason for this behaviour but again it looks more like a bug on my end that I have to avoid triggering.

**Comment by brandur** [comment] 2016-10-17 20:58
@gsakkis I thought based on your original report that it was implied that this is a documentation problem. Digging in a little more deeply though, it seems that this is particular to shipping information on customers and how updates are handled on it. Given that it's not really consistent with behavior elsewhere in the API right now, I think it makes sense to try and change this.

I've opened an internal PR on the server which will hopefully go live soon.

**Comment by brandur** [comment] 2016-10-17 21:49
Change deployed.

**Comment by gsakkis** [comment] 2016-10-18 14:09
Thanks for looking further into it but it still doesn't work for me (at least without my changes that work around the issue), still getting "Missing required param: name." if i try to update, say, just the shipping phone number.

**Comment by brandur** [comment] 2016-10-26 23:41
Hm, quite right, I think I missed a piece of the implementation and my test didn't catch it. I'm running another patch through to see if I can get it fixed for real this time.
