### ISSUE TITLE
Intermittent APIConnectionError: Could not verify Stripe's SSL certificate

### ISSUE THREAD

**Issue by mihaiz-eggnita** [stripe/stripe-python#726] opened 2021-06-18 09:16 UTC
Some of the requests made from our application running on Heroku and using Python 3.9.2 and your library's version 2.56.0 get this exception.

_HTTPSConnectionPool(host='api.stripe.com', port=443): Max retries exceeded with url: /v1/customers/<some-id>?expand%5B0%5D=default_source (Caused by SSLError(SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2622)')))_

_APIConnectionError: Could not verify Stripe's SSL certificate.  Please make sure that your network is not intercepting certificates.  If this problem persists, let us know at support@stripe.com._ 

Most of the requests do work, but we get this intermittently for some of them. I did write to support, but they needed an event ID that I did not have to trace the problem and I figured that since the request doesn't even reach their server this is the better place to ask.

**Comment by ob-stripe** [comment] 2021-06-18 17:03
Hi @mihaiz-eggnita. Are you making any changes to `stripe.ca_bundle_path` or doing anything at all that could affect TLS certificate validation?

**Comment by mihaiz-eggnita** [comment] 2021-06-24 08:36
@ob-stripe thank you for your reply and I am sorry for me being late. No, we are doing no such thing to affect the certificate.

**Comment by mihaiz-eggnita** [comment] 2021-07-02 08:10
@ob-stripe do you have any idea what I could do about this? Or is there any info I could give to provide more insight? 

I checked the logs and it seems that first showed up on the 28th of May at 10:38 AM UTC and it keeps happening to around 10-20 requests every day..

**Comment by ob-stripe** [comment] 2021-07-02 16:05
@mihaiz-eggnita Does your application use multiple threads? I've never seen this error before but I found some posts suggesting that it could be an issue with the HTTP client not being fully thread-safe.

**Comment by mihaiz-eggnita** [comment] 2021-07-05 13:26
@ob-stripe in only one use case we are using threading, but we are having this issue in others also and it sounds like if that was the case other parts of the app would have been affected

But we can try to investigate this case also. Do you know any workaround that we could use?

**Comment by ob-stripe** [comment] 2021-07-07 21:22
Unfortunately all of the reports I could find that mention this error seem to indicate that it's a transient error that goes away if you retry later, try on a different connection or a different computer, etc. Of course this is not applicable to a production server :(

One thing you can try to alleviate the issue is enable [automatic retries](https://github.com/stripe/stripe-python#configuring-automatic-retries):
```python
import stripe

stripe.max_network_retries = 2
```

**Comment by mihaiz-eggnita** [comment] 2021-07-21 10:27
@ob-stripe sorry for the delay, I was away for a while.. it seems that is exactly what we are already doing, so I guess there's no other solution.. thank you for your time anyway!

**Comment by richardm-stripe** [comment] 2022-01-18 20:45
Closing as I don't think there is anything actionable here on Stripe's end.

**Closed by richardm-stripe** 2022-01-18 20:45 UTC
