### ISSUE TITLE
Trailing newline in stripe.api_key makes POST data disappear

### ISSUE THREAD

**Issue by Yuffster** [stripe/stripe-python#334] opened 2017-07-17 00:04 UTC
So I've spent a bit of time scratching my head over a strange bug in which none of my customer emails were being saved.  Looking in the request log dashboard, the POST data was blank.

Eventually I figured it out.

If I use `stripe.api_key =` to set the key with a newline at the end of the string, it seems to cause the POST data to get lost somewhere along the pipeline (see [line 11 of this gist](https://gist.github.com/Yuffster/d87e422c3c6d5b90b1b97339f66b57a1/eccd3f38a66b711e1947f01ea2a3767e4a8bcea1#file-customer-py-L11)).

However, if I run`.strip()` on my API key string, it works as expected (again, [line 11](https://gist.github.com/Yuffster/d87e422c3c6d5b90b1b97339f66b57a1/7526f4ab90c6dabfbb47c44baea67d34d1536d60#file-customer-py-L11); notice the output includes the email and description).

**Comment by ob-stripe** [comment] 2017-07-18 10:51
@Yuffster That's weird. If I append a `\n` newline after the API key, then API requests fail with:
> APIConnectionError: Unexpected error communicating with Stripe. It looks like there's
probably a configuration issue locally.  If this problem persists, let
us know at support@stripe.com.
> 
> (Network error: A ValueError was raised with error message Invalid header value 'Bearer sk_test_...\n')

which is expected behavior.

When appending a Windows line ending `\r\n`, I get a similar error:
> APIConnectionError: Unexpected error communicating with Stripe.  If this problem persists,
let us know at support@stripe.com.
> 
> (Network error: InvalidHeader: Invalid return character or leading space in header: Authorization)

In that second case, the request is not even fired as the issue is caught locally by [requests](https://github.com/requests/requests/blob/132040cc0378a787916474c33a7c9f693806a92f/requests/utils.py#L869).

Could you provide the following information?

- your Python version (`python --version`)
- your stripe-python version (`python -c "import stripe; print(stripe.VERSION)"`)
- which underlying HTTP library you're using (`python -c "import stripe; print(type(stripe.http_client.new_default_http_client()))"`)
- the contents of your `~/.keys/stripe_test` file. You should redact the API key itself, but clarify whether there's anything else in the file, including newline characters (and if so, whether they're CR/LF/CRLF).

**Comment by brandur-stripe** [comment] 2017-07-18 17:53
This isn't going to be too helpful, but I wrote my own repro script for this yesterday, and came up with the same result as you, Olivier.

I think there's some argument that we could just strip these values before making requests (or as they're set), but given that the error is relatively sane, it doesn't seem to be too critical of an addition.

**Comment by ob-stripe** [comment] 2017-10-16 12:38
I'm closing the issue, but feel free to reply if you can provide more information to help us reproduce the problem.

**Closed by ob-stripe** 2017-10-16 12:38 UTC
