### ISSUE TITLE
Leaking connections

### ISSUE THREAD

**Issue by outcoldman** [stripe/stripe-python#432] opened 2018-06-03 21:14 UTC
In case of when by default `RequestsClient` is used https://github.com/stripe/stripe-python/blob/master/stripe/http_client.py#L101 you are leaking connection by creating new Session object for every request. But never calling `RequestsClient.close`.

The workaround is simple you need to initialize `default_http_client` to make sure that library is going to reuse sessions between calls.  

To fix this issue, I guess there are three options:

1. Change APIRequestor code to cache the `default_http_client` if it is `None`. https://github.com/stripe/stripe-python/blob/master/stripe/api_requestor.py#L78

2. Make sure that every time you create new APIRequestor - you close the client at the end.

3. Do not create sessions in RequestsClient.

**Comment by ob-stripe** [comment] 2018-06-04 09:53
Hi @outcoldman, thanks for the report! This is a known issue, which I'm hoping to fix with some refactoring in the upcoming v2 of the library. Tagging this as `future` for now.

**Comment by Alexander3** [comment] 2018-11-28 21:30
As you said workaround is :
```python
import stripe
from stripe.http_client import RequestsClient
stripe.default_http_client = RequestsClient(verify_ssl_certs=True)
```
This fixes multiple `Starting new HTTPS connection (1): api.stripe.com:443`
Not that huge performance improvement but still worthy.

**Comment by ob-stripe** [comment] 2019-02-02 11:08
As of version 2.20.0, stripe-python reuses HTTP clients, which should prevent connections leaking.

Closing this issue, but feel free to reply if you think the problem is still present.

**Closed by ob-stripe** 2019-02-02 11:08 UTC
Labels: future
